// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// StatsIncrementer is an autogenerated mock type for the StatsIncrementer type
type StatsIncrementer struct {
	mock.Mock
}

// Increment provides a mock function with given fields: bucket
func (_m *StatsIncrementer) Increment(bucket string) {
	_m.Called(bucket)
}
